### ISSUE TITLE
Recipe Ingredients are not scraping correctly for the website barefootcontessa.com

### ISSUE THREAD

**Issue by priyatham1188** [hhursev/recipe-scrapers#880]
**Pre-filing checks**

- [ ] I have searched for open issues that report the same problem : I didn't found any of such 
- [ ] I have checked that the bug affects the latest version of the library: I am not sure about this 

**The URL of the recipe(s) that are not being scraped correctly**
https://barefootcontessa.com/recipes/roasted-vegetable-lasagna
https://barefootcontessa.com/recipes/parmesan-chicken

...

**The results you expect to see**
This is the response from other website and you can see here it has scraped correctly as seperate array elements unlike the issue website where it concatenated for some reason.

['1 cup dry black beans ((or sub 2 15-oz. cans black beans // amount as recipe is written — adjust as needed))', '1 cup uncooked brown rice ((~3 cups cooked rice // amount as recipe is written — adjust as needed))', '1 small bundle kale, chopped, large stems removed', '1 batch Gingery Lemon Tahini Sauce', '3/4 cup Cabbage Apple Sauerkraut', '1 small bundle green onion, thinly sliced', '1 ripe avocado, sliced', '4 Tbsp sea vegetable of choice ((optional // we prefer dulse or nori, crumbled or chopped))', '4 tsp sesame seeds, divided ((optional))']

...

**The results (including any Python error messages) that you are seeing**
This is how the ingredients are getting scraped as one string instead of multiple strings and with this response there isnt any way I can seperate the ingredients 
['1½ pounds eggplant, unpeeled, sliced lengthwise ¼ inch thick ¾ pound zucchini, unpeeled, sliced lengthwise ¼ inch thick ⅔ cup good olive oil 1 tablespoon dried oregano Kosher salt and freshly ground black pepper 1 tablespoon minced garlic (3 cloves) 10 ounces lasagna noodles, such as De Cecco 16 ounces fresh whole-milk ricotta 8 ounces creamy garlic and herb goat cheese, at room temperature 2 extra-large eggs, lightly beaten ½ cup chopped fresh basil leaves, lightly packed 1 cup freshly grated Parmesan cheese, divided 4½ cups good bottled marinara sauce, such as Rao’s (40 ounces) 1 pound lightly salted fresh mozzarella, very thinly sliced']
...

Team , can you please look into this and help me with this issue ?

**Comment by priyatham1188** [comment]
@jknndy @jayaddison  Thanks for the quick work and merging it , However I have a quick question when these updates were made , are these released as part of a new release or how this reflect because I still see the same issue ?

**Comment by jayaddison** [comment]
Hi @priyatham1188 - yep, this functionality will be released in an updated version of the library soon.

Since there are a few changes ready for release, I'll go ahead and do that within the next 10-15 mins or so.

**Comment by jayaddison** [comment]
Ok: this issue should be resolved by version 14.50.1 of the library, as available on PyPi.

**Comment by priyatham1188** [comment]
@jayaddison  Thanks a lot for ur help and I think it will take some time to reflect on PYPI as it still showing 14.49.4 as the latest version and throwing an error when I m trying to upgrade to this version on my local .
 I have another question where our project is using 13.12.1 and I just want to understand will there be any problem if I upgrade to this new version .

**Comment by jayaddison** [comment]
@priyatham1188 ah, weird: I entered the wrong version number into the `__version__` file; 14.45.1 instead of 14.50.1 - my mistake.  I've republished the correct version as `14.50.2`.

### Upgrade
I think that the upgrade between 13.12.1 and 14.49.x (or the upcoming 14.50.1) should be fairly smooth, but I can't guarantee it.  I'd recommend taking a look at a diff between the two versions, like this one: https://github.com/hhursev/recipe-scrapers/compare/13.12.1...14.49.0

(a chunk of documentation was added in 14.49.1 so I thought it might save you some reading time to link to a smaller diff before they were added)

What to look for in that comparison is down to the way that you use the library.  One thing I'd note is that there are one or two plugin removals (`Bcp47ValidatePlugin`, `SchemaOrgPriorityPlugin`), so if you've been relying on those, that could require some attention before an upgrade.
